services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~20.11.1
      - key: NODE_ENV
        value: production
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: DATABASE_NAME
        fromDatabase:
          name: strapi
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: strapi
          property: host
          isOptional: true
      - key: DATABASE_PORT
        fromDatabase:
          name: strapi
          property: port
          isOptional: true
      - key: DATABASE_USERNAME
        fromDatabase:
          name: strapi
          property: user
          isOptional: true
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: strapi
          property: password
          isOptional: true
      - key: DATABASE_SSL
        fromDatabase:
          name: strapi
          property: ssl
          isOptional: true
      - key: SUPABASE_API_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi
    plan: starter
